### PR TITLE
Update python in venv to 3.10

### PR DESCRIPTION
**Pull request by jonathansberry**
## Description

I stumbled across errors with parts of ansible not being compatible with python 3.8 when trying to resync my fjelltopp-ansible pipenv. 

I tried simply setting the python version to 3.10, and at the moment everything appears to work. 

Proposing we maybe don't merge immediately, so that I can do a bit more testing?

## Dependency Changes

python version in the pipfile changed to 3.10. 

## Testing

Mannual testing underway. 

## Checklist

Put an `x` in the boxes that apply to this pull request (you can also fill these out after opening the pull request).
You may not need to check all boxes.

- [x] The Jira ticket for this issue has been updated to "Ready to Review" or equivalent.
- [x] I have developed these changes in discussion with the appropriate project manager.
- [x] My code follows the general Fjelltopp documentation (see Confluence).
- [x] I have made corresponding changes to the Fjelltopp documentation (see Confluence).
- [x] I have rebased this branch with master.
- [x] New dependency changes have been committed.
- [x] I have added automated tests that prove my fix is effective or that my feature works.
- [x] New and existing tests pass locally with my changes.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own code.
- [x] I have assigned at least one reviewer.
- [x] I have assigned at least one label to this PR: "patch", "minor", "major".

### CODE REVIEW

**Comment by ChasNelson1990** [comment]
> Proposing we maybe don't merge immediately, so that I can do a bit more testing?

Agreed - maybe we come back to this in 2 weeks?

**Comment by jonathansberry** [comment]
@ntwalibas Has duplicated this change here: https://github.com/fjelltopp/fjelltopp-ansible/pull/42

**Review by ChasNelson1990 — APPROVED** [review]
LGTM - let's get this merged and it can be thoroughly tested for Zambia and Romania today

**Comment by ChasNelson1990** [comment]
Merging on your behalf @jonathansberry so we can test as part of the fjelltopp/dms#54 fixes roll out to Zambia and Romania

**Comment by ChasNelson1990** [comment]
@jonathansberry - you ticked:
>  I have assigned at least one label to this PR: "patch", "minor", "major".

But you actually didn't - not everything needs to be ticked but please don't tick things if they aren't accurate.

**Comment by ChasNelson1990** [comment]
This actually probably should have been a major change because it will break venvs

**Pull request merged**
