### PR TITLE
WRC-69 Fix resolvelib to a valid version

### PR DESCRIPTION
**Pull request by jonathansberry**
## Description

WRC (Romania) jenkins deployments have been failing with the following error:
```
ERROR! ansible-galaxy requires resolvelib<0.9.0,>=0.5.3
```
The pipfile lock in fjelltopp ansible says that resolve lib is set at 1.0.1 - i.e. outside what ansible-galaxy requires. 

Surely pipenv/pip's job is to resolve this properly? 

Anyhows... doing a simple `pipenv install resolvelib==0.8.1` seems to fix this issue (see logs [here](https://ci.fjelltopp.org/job/WHORomaniaCkan-deploy/61/console)). `0.8.1` was the version of resolve lib we had previously in the pipfile.lock.  I have therefore relocked the pipfile with this change.

I've ensured I lock the pipfile with the same version of pipenv used on jenkins (`pip install pipenv=2021.11.23`) but are we using this version in Azure?

Merging this and bumping fjelltopp-ansible in infrastructure will fix WRC deployments in Jenkins. 

## Dependency Changes

Changes the version of resolvelib and relocks pipfile. 

## Testing

I have deployed WHO romania with this new pipfile lock from jenkins (e.g. [here](https://ci.fjelltopp.org/job/WHORomaniaCkan-deploy/71/)) and it worked well. I have not tested other projects and Azure though. 

## Checklist

Put an `x` in the boxes that apply to this pull request (you can also fill these out after opening the pull request).
You may not need to check all boxes.

- [ ] The Jira ticket for this issue has been updated to "Ready to Review" or equivalent.
- [ ] I have developed these changes in discussion with the appropriate project manager.
- [ ] My code follows the general Fjelltopp documentation (see Confluence).
- [ ] I have made corresponding changes to the Fjelltopp documentation (see Confluence).
- [ ] I have rebased this branch with master.
- [ ] New dependency changes have been committed.
- [ ] I have added automated tests that prove my fix is effective or that my feature works.
- [ ] New and existing tests pass locally with my changes.
- [ ] My changes generate no new warnings.
- [ ] I have performed a self-review of my own code.
- [ ] I have assigned at least one reviewer.
- [ ] I have assigned at least one label to this PR: "patch", "minor", "major".

### CODE REVIEW

**Comment by cooper667** [comment]
>Surely pipenv/pip's job is to resolve this properly?

That would be nice!

**Review by ChasNelson1990 — DISMISSED** [review]
LGTM. The reason Pipenv has not handled this is because we aren't installing ansible-galaxy through pipenv... well it's not in the lockfile anyway... does ansible pull this in somewhere else?

**Comment by cooper667** [comment]
> LGTM. The reason Pipenv has not handled this is because we aren't installing ansible-galaxy through pipenv... well it's not in the lockfile anyway... does ansible pull this in somewhere else?

Galaxy comes with ansible. Is it possible (and more importantly, sensible) to move [these](https://github.com/fjelltopp/fjelltopp-ansible/blob/master/roles/requirements.yml) to pip?

**Comment by ChasNelson1990** [comment]
> Galaxy comes with ansible. Is it possible (and more importantly, sensible) to move [these](https://github.com/fjelltopp/fjelltopp-ansible/blob/master/roles/requirements.yml) to pip?

Don't think we can... they aren't python packages per se, right... they are cascades of never ending ansible galaxy ymls, right?

**Comment by ChasNelson1990** [comment]
@mixmixmix leaving for you to rebase

**Review by ChasNelson1990 — APPROVED** [review]
LGTM

**Pull request merged**
